version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo apt update && sudo apt install -y unzip
      - run: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
      - run:
          name: Install MySQL driver
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "src/composer.json" }} 
            - composer-v1-
      - run: cd src && composer install -n --prefer-dist 
      - save_cache:
          key: composer-v1-{{ checksum "src/composer.json" }} 
          paths:
            - vendor
      - run: 
          name: Run tests and conditionally pull from git
          command: cd src && php artisan test && git pull origin main
